// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: EventService_v1.proto

package event_v1

import (
	context "context"
	"github.com/antondoinikov/calendar-server/hw12_13_14_15_calendar/internal/app/api/event_v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EventV1Client is the client API for EventV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventV1Client interface {
	CreateEvent(ctx context.Context, in *CreateEventRequest, opts ...grpc.CallOption) (*CreateEventResponse, error)
	UpdateEvent(ctx context.Context, in *UpdateEventRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteEvent(ctx context.Context, in *DeleteEventRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetListEvent(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetListEventResponse, error)
	GetListWeekEvent(ctx context.Context, in *GetListWeekEventRequest, opts ...grpc.CallOption) (*GetListWeekEventResponse, error)
	GetListMonthEvent(ctx context.Context, in *GetListMonthEventRequest, opts ...grpc.CallOption) (*GetListMonthEventResponse, error)
}

type eventV1Client struct {
	cc grpc.ClientConnInterface
}

func NewEventV1Client(cc grpc.ClientConnInterface) EventV1Client {
	return &eventV1Client{cc}
}

func (c *eventV1Client) CreateEvent(ctx context.Context, in *CreateEventRequest, opts ...grpc.CallOption) (*CreateEventResponse, error) {
	out := new(CreateEventResponse)
	err := c.cc.Invoke(ctx, "/event_v1.EventV1/CreateEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventV1Client) UpdateEvent(ctx context.Context, in *UpdateEventRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/event_v1.EventV1/UpdateEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventV1Client) DeleteEvent(ctx context.Context, in *DeleteEventRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/event_v1.EventV1/DeleteEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventV1Client) GetListEvent(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetListEventResponse, error) {
	out := new(GetListEventResponse)
	err := c.cc.Invoke(ctx, "/event_v1.EventV1/GetListEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventV1Client) GetListWeekEvent(ctx context.Context, in *GetListWeekEventRequest, opts ...grpc.CallOption) (*GetListWeekEventResponse, error) {
	out := new(GetListWeekEventResponse)
	err := c.cc.Invoke(ctx, "/event_v1.EventV1/GetListWeekEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventV1Client) GetListMonthEvent(ctx context.Context, in *GetListMonthEventRequest, opts ...grpc.CallOption) (*GetListMonthEventResponse, error) {
	out := new(GetListMonthEventResponse)
	err := c.cc.Invoke(ctx, "/event_v1.EventV1/GetListMonthEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventV1Server is the server API for EventV1 service.
// All implementations must embed UnimplementedEventV1Server
// for forward compatibility
type EventV1Server interface {
	CreateEvent(context.Context, *CreateEventRequest) (*CreateEventResponse, error)
	UpdateEvent(context.Context, *UpdateEventRequest) (*emptypb.Empty, error)
	DeleteEvent(context.Context, *DeleteEventRequest) (*emptypb.Empty, error)
	GetListEvent(context.Context, *emptypb.Empty) (*GetListEventResponse, error)
	GetListWeekEvent(context.Context, *GetListWeekEventRequest) (*GetListWeekEventResponse, error)
	GetListMonthEvent(context.Context, *GetListMonthEventRequest) (*GetListMonthEventResponse, error)
	mustEmbedUnimplementedEventV1Server()
}

// UnimplementedEventV1Server must be embedded to have forward compatible implementations.
type UnimplementedEventV1Server struct {
}

func (UnimplementedEventV1Server) CreateEvent(context.Context, *CreateEventRequest) (*CreateEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEvent not implemented")
}
func (UnimplementedEventV1Server) UpdateEvent(context.Context, *UpdateEventRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEvent not implemented")
}
func (UnimplementedEventV1Server) DeleteEvent(context.Context, *DeleteEventRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEvent not implemented")
}
func (UnimplementedEventV1Server) GetListEvent(context.Context, *emptypb.Empty) (*GetListEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetListEvent not implemented")
}
func (UnimplementedEventV1Server) GetListWeekEvent(context.Context, *GetListWeekEventRequest) (*GetListWeekEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetListWeekEvent not implemented")
}
func (UnimplementedEventV1Server) GetListMonthEvent(context.Context, *GetListMonthEventRequest) (*GetListMonthEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetListMonthEvent not implemented")
}
func (UnimplementedEventV1Server) mustEmbedUnimplementedEventV1Server() {}

// UnsafeEventV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventV1Server will
// result in compilation errors.
type UnsafeEventV1Server interface {
	mustEmbedUnimplementedEventV1Server()
}

func RegisterEventV1Server(s grpc.ServiceRegistrar, srv *event_v1.Implementation) {
	s.RegisterService(&EventV1_ServiceDesc, srv)
}

func _EventV1_CreateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventV1Server).CreateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event_v1.EventV1/CreateEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventV1Server).CreateEvent(ctx, req.(*CreateEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventV1_UpdateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventV1Server).UpdateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event_v1.EventV1/UpdateEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventV1Server).UpdateEvent(ctx, req.(*UpdateEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventV1_DeleteEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventV1Server).DeleteEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event_v1.EventV1/DeleteEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventV1Server).DeleteEvent(ctx, req.(*DeleteEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventV1_GetListEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventV1Server).GetListEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event_v1.EventV1/GetListEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventV1Server).GetListEvent(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventV1_GetListWeekEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListWeekEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventV1Server).GetListWeekEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event_v1.EventV1/GetListWeekEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventV1Server).GetListWeekEvent(ctx, req.(*GetListWeekEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventV1_GetListMonthEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListMonthEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventV1Server).GetListMonthEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event_v1.EventV1/GetListMonthEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventV1Server).GetListMonthEvent(ctx, req.(*GetListMonthEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventV1_ServiceDesc is the grpc.ServiceDesc for EventV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "event_v1.EventV1",
	HandlerType: (*EventV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEvent",
			Handler:    _EventV1_CreateEvent_Handler,
		},
		{
			MethodName: "UpdateEvent",
			Handler:    _EventV1_UpdateEvent_Handler,
		},
		{
			MethodName: "DeleteEvent",
			Handler:    _EventV1_DeleteEvent_Handler,
		},
		{
			MethodName: "GetListEvent",
			Handler:    _EventV1_GetListEvent_Handler,
		},
		{
			MethodName: "GetListWeekEvent",
			Handler:    _EventV1_GetListWeekEvent_Handler,
		},
		{
			MethodName: "GetListMonthEvent",
			Handler:    _EventV1_GetListMonthEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "EventService_v1.proto",
}
